---
#Provision some instances:
- hosts: all
  connection: local
  gather_facts: False

  vars_files:
  - group_vars/all
 
  tasks:
  - name: Launch raw instances
    ec2: >
     access_key="{{ ec2_access_key }}"
     secret_key="{{ ec2_secret_key }}"
     keypair="{{ ec2_keypair }}"
     type="{{ ec2_instance_type }}"
     image="{{ ec2_image }}"
     region="{{ ec2_region }}"
     instance_tags="{'ansible_group':'{{ ansible_group }}', 'group':'{{ ec2_security_group }}','Name':'{{ server_type }}' }"
     count="{{ ec2_instance_count }}"
     group_id="{{ec2_security_group}}"
     assign_public_ip="{{assign_public_ip}}"
     vpc_subnet_id="{{vpc_subnet_id}}"
     wait=true
    register: ec2

  - name: Wait for SSH to come up
    local_action: wait_for host={{ item.public_dns_name }}
      port=22 delay=60 timeout={{ aws_timeout }} state=started
    with_items: ec2.instances
